# -*- coding: utf-8 -*-
"""Yulia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgHlkndqq7T2i7a07kRK7SoUrN3oMwX-
"""

import pandas as pd
df1 = pd.read_csv("studierende.csv", sep=";")
df2 = pd.read_csv("pruefung.csv", sep=";")

df1.head()

df2.head()

df1.info()

df2.info()

df1.isna().sum()

df2.isna().sum()

# Fehlende Werte in Prozent (tabelle studierende)
df1.isna().mean() * 100

# Fehlende Werte in Prozent (tabelle pruefung)
df2.isna().mean() * 100

#Betroffene Zeilen (tabelle studierende)
df1[df1.isna().any(axis=1)]

#Betroffene Zeilen (tabelle pruefung)
df2[df2.isna().any(axis=1)]

df2_absolventen = df2[df2["variable"] == "pruefungsabschluesse"].dropna()
df2_absolventen



#Datentyp (studierende)
df1.dtypes

#Datentyp (pruefungen)
df2.dtypes

df1["semester"].unique()
df1["variable"].unique()

#Kategorien als category speichen (studierende)
df1["semester"] = df1["semester"].astype("category")
df1["variable"] = df1["variable"].astype("category")

#Kategorien als category speichen (pruefungen)
df2["variable"] = df2["variable"].astype("category")

# neue variable sonstige
df1["sonstige"] = df1["gesamt"] - df1["bachelor"] - df1["master"]

#neue variable anteil_bachelor
df1["anteil_bachelor"] = df1["bachelor"] / df1["gesamt"]
df1['anteil_bachelor']

#neue variable anteil_master
df1["anteil_master"] = df1["master"] / df1["gesamt"]

#neue variable anteil_sonstige
df1["anteil_sonstige"] = df1["sonstige"] / df1["gesamt"]

df1.head()
df1.info()

df1_exmats = df1[df1["variable"] == "exmatrikulationen"].dropna()
numeric_cols = ['bachelor', 'master', 'gesamt', 'sonstige',	'anteil_bachelor',	'anteil_master',	'anteil_sonstige']  # numeric columns only

df1_exmats_per_year = (
    df1_exmats
        .groupby("jahr", as_index=False)  # keep Jahr as column
        .agg(
            {**{col: 'mean' for col in numeric_cols},  # compute mean for numeric cols
            #  "Semester": "first",                    # pick first value (or other rule) for non-numeric
            #  "Variable": "first"
             }                    # same for Variable
        ).round(2)
)
df1_exmats_per_year

abschluesse = df2_absolventen	[["jahr", "bachelor_gesamt", "master_gesamt"]]
exmat = df1_exmats_per_year[["jahr", "bachelor", "master"]]

# 2. Nach Jahr zusammenführen
df_kombiniert = abschluesse.merge(exmat, on="jahr", how="inner")

# 3. Optional: umbenennen für Klarheit
df_kombiniert = df_kombiniert.rename(columns={
    "jahr": "Jahr",
    "bachelor_gesamt": "Bachelor_Abschlüsse",
    "master_gesamt": "Master_Abschlüsse",
    "bachelor": "Bachelor_Exmatrikulationen",
    "master": "Master_Exmatrikulationen"
})
df_kombiniert

# Gesamtzahl der Abgänge pro Jahr berechnen
df_kombiniert["Bachelor_Gesamt_Abgänge"] = (
    df_kombiniert["Bachelor_Abschlüsse"] +
    df_kombiniert["Bachelor_Exmatrikulationen"]
)

df_kombiniert["Master_Gesamt_Abgänge"] = (
    df_kombiniert["Master_Abschlüsse"] +
    df_kombiniert["Master_Exmatrikulationen"]
)

# Absolventenquote
df_kombiniert["Bachelor_Absolventenquote"] = (
    df_kombiniert["Bachelor_Abschlüsse"] /
    df_kombiniert["Bachelor_Gesamt_Abgänge"]
)

df_kombiniert["Master_Absolventenquote"] = (
    df_kombiniert["Master_Abschlüsse"] /
    df_kombiniert["Master_Gesamt_Abgänge"]
)

# Abbruchquote
df_kombiniert["Bachelor_Abbruchquote"] = (
    df_kombiniert["Bachelor_Exmatrikulationen"] /
    df_kombiniert["Bachelor_Gesamt_Abgänge"]
)

df_kombiniert["Master_Abbruchquote"] = (
    df_kombiniert["Master_Exmatrikulationen"] /
    df_kombiniert["Master_Gesamt_Abgänge"]
)

quote_cols = [
    "Bachelor_Absolventenquote",
    "Master_Absolventenquote",
    "Bachelor_Abbruchquote",
    "Master_Abbruchquote"
]

# df_kombiniert[quote_cols] = df_kombiniert[quote_cols] * 100
df_kombiniert[quote_cols] = (
    df_kombiniert[quote_cols] * 100
).round(2)
df_abschluss_daten = df_kombiniert[quote_cols]
df_abschluss_daten

# 10 jahre analyse für gesamt studierende
df1_gesamt = df1[df1["variable"] == "studierende_gesamt"]
df1_gesamt

# jahresdurchschnitt
# df1_jahr = (
#     df1_gesamt
#         .groupby("jahr")["gesamt"]
#         .mean()
#         .reset_index()
# )
# df1_jahr

numeric_cols = ['bachelor', 'master', 'gesamt', 'sonstige',	'anteil_bachelor',	'anteil_master',	'anteil_sonstige']  # numeric columns only

df1_jahr = (
    df1_gesamt
        .groupby("jahr", as_index=False)  # keep Jahr as column
        .agg(
            {**{col: 'mean' for col in numeric_cols},  # compute mean for numeric cols
            #  "Semester": "first",                    # pick first value (or other rule) for non-numeric
            #  "Variable": "first"
             }                    # same for Variable
        )
)

df1_jahr

#Prozentuale Veränderung zum Vorjahr (wachstum)
df1_jahr["wachstum_%"] = (
    df1_jahr["gesamt"].pct_change() * 100
)
df1_jahr["wachstum_%"]

#absolute Veränderung
df1_jahr["veraenderung"] = df1_jahr["gesamt"].diff()
df1_jahr['veraenderung']

#Mögliche Visualisierungen 1)gesamtzahl 2)Wachstum 3) absolute Veränderung

# 2. Ausländer (nur wintersemester)
df1_ws = df1[df1["semester"].str.contains("WS")]

# 2. Ausländer
#filltern variable gesamt und Ausländer
df1_relevant = df1[df1["variable"].isin([
    "studierende_gesamt",
    "studierende_auslaendisch"
])]

# Tabelle pro jahr
# filter für WiSe
df_winter_semester_relevant = df1[
    (df1["semester"] == "WiSe") &
    (df1["variable"].isin(["studierende_gesamt", "studierende_auslaendisch"]))
]

# pivot
df1_grouped = df_winter_semester_relevant.pivot(
    index="jahr",
    columns="variable",
    values="gesamt"
)

#Berechnung Ausländeranteil
df1_grouped["auslaenderanteil_%"] = (
    df1_grouped["studierende_auslaendisch"] /
    df1_grouped["studierende_gesamt"] * 100
)

#Veränderung zur Vorjahr %
df1_grouped["veraenderung_prozentpunkte"] = (
    df1_grouped["auslaenderanteil_%"].diff()
)
#Visualisirung

# 3.Frauenanteil

df_calculated_frauenanteil = df1[df1["variable"].isin(["studierende_weiblich", "studierende_gesamt"])]

# Pivot the data to have 'studierende_weiblich' and 'studierende_gesamt' as columns
df_pivot_frauen = df_calculated_frauenanteil.pivot_table(
    index=['jahr', 'semester'],
    columns='variable',
    values='gesamt'
).reset_index()

# Calculate 'frauenanteil_%'
df_pivot_frauen['frauenanteil_%'] = (
    df_pivot_frauen['studierende_weiblich'] / df_pivot_frauen['studierende_gesamt'] * 100
)

# Select only the relevant columns from df_pivot_frauen for merging
df_frauen_for_merge = df_pivot_frauen[['jahr', 'semester', 'frauenanteil_%']]

# Merge with df1
df1 = pd.merge(df1, df_frauen_for_merge, on=['jahr', 'semester'], how='left')

